using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Taciturn;

/// <summary>
/// Emits a PrintMembers override that redacts every member of a [Taciturn]-marked
/// record, so a property added later is redacted by default rather than by
/// remembering to update a hand-maintained list.
///
/// Phase 4 (see plan.md, final phase): [Plain] opts an individual member back
/// into the clear - default stays "everything redacted". TACIT004 warns when an
/// unmarked record derives from a marked one, since protection is per-type, not
/// per-hierarchy. A [DebuggerTypeProxy] is emitted too, so a debugger hover shows
/// the same redacted view ToString() does.
/// </summary>
[Generator]
public sealed class TaciturnGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Taciturn.TaciturnAttribute";
    private const string PlainAttributeFullName = "Taciturn.PlainAttribute";

    // A member name can never legally contain '~', so it doubles as the
    // encode/decode marker for "this member carries [Plain]" without needing
    // a second parallel array field on Candidate — everything the pipeline
    // caches still has to be a single flat, value-equatable string.
    private const char PlainMarker = '~';

    private const string AttributeSource = """
        // <auto-generated/>
        #nullable enable
        namespace Taciturn
        {
            /// <summary>
            /// Marks a partial record whose members are redacted in ToString()/PrintMembers()
            /// by default. Use [Plain] on an individual member (including
            /// [property: Plain] on a positional-record parameter) to opt it back
            /// into the clear.
            /// </summary>
            [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Struct, Inherited = false, AllowMultiple = false)]
            public sealed class TaciturnAttribute : System.Attribute
            {
            }

            /// <summary>
            /// Opts one member of a [Taciturn] record back into the clear. On a
            /// positional record parameter, apply it as [property: Plain] - the
            /// attribute targets the synthesized property, not the parameter.
            /// </summary>
            [System.AttributeUsage(System.AttributeTargets.Property | System.AttributeTargets.Field, Inherited = false, AllowMultiple = false)]
            public sealed class PlainAttribute : System.Attribute
            {
            }
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("TaciturnAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

        // The transform below extracts only primitive, structurally-equatable data
        // (strings/bools/one Location) from the symbol and syntax node. Candidate
        // must never hold an ISymbol or SyntaxNode directly: Roslyn hands out a new
        // instance of both on every compilation even when a type's source hasn't
        // changed, so a pipeline value that captures them can never compare equal
        // to its previous run — RegisterSourceOutput's caching is defeated and
        // every [Taciturn] type in the whole compilation regenerates on every
        // keystroke anywhere in the project, not just edits to that type.
        IncrementalValuesProvider<Candidate> candidates = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is TypeDeclarationSyntax,
                transform: static (ctx, _) =>
                {
                    var decl = (TypeDeclarationSyntax)ctx.TargetNode;
                    var symbol = (INamedTypeSymbol)ctx.TargetSymbol;

                    return new Candidate(
                        Name: symbol.Name,
                        TypeParametersDisplay: symbol.TypeParameters.Length > 0
                            ? string.Join(", ", symbol.TypeParameters.Select(t => t.Name))
                            : "",
                        Namespace: symbol.ContainingNamespace is { IsGlobalNamespace: false } ns
                            ? ns.ToDisplayString()
                            : null,
                        IsPartial: decl.Modifiers.Any(SyntaxKind.PartialKeyword),
                        IsRecord: symbol.IsRecord,
                        IsRecordStruct: symbol.IsValueType,
                        IsSealed: symbol.IsSealed,
                        // A record struct's BaseType is System.ValueType, which is
                        // never itself IsRecord, so this comes out false for structs
                        // without needing a separate guard against them here.
                        DerivesFromAnotherRecord: symbol.BaseType is { IsRecord: true },
                        AlreadyHasPrintMembersOrToString: HasUserDeclaredPrintMembersOrToString(symbol),
                        EncodedMembers: string.Join(" ", GetPrintableMembers(symbol).Select(Encode)),
                        Location: decl.Identifier.GetLocation());
                });

        context.RegisterSourceOutput(candidates, static (spc, candidate) => Execute(spc, candidate));

        // TACIT004: a separate, unfiltered pipeline over every type declaration
        // with a base list - it has to look at types that are NOT [Taciturn]-
        // marked (that's the whole point), so it can't reuse the
        // ForAttributeWithMetadataName provider above, which only ever sees
        // marked types. Each candidate still resolves everything it needs to a
        // primitive DerivedCandidate at transform-time, for the same caching
        // reason as the main pipeline.
        IncrementalValuesProvider<DerivedCandidate> unmarkedDerived = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is TypeDeclarationSyntax { BaseList.Types.Count: > 0 },
                transform: static (ctx, _) =>
                {
                    var decl = (TypeDeclarationSyntax)ctx.Node;
                    if (ctx.SemanticModel.GetDeclaredSymbol(decl) is not INamedTypeSymbol symbol || !symbol.IsRecord)
                        return default;

                    bool selfMarked = symbol.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == AttributeFullName);
                    bool baseMarked = symbol.BaseType is { } bt && bt.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == AttributeFullName);

                    return selfMarked || !baseMarked
                        ? default
                        : new DerivedCandidate(symbol.Name, decl.Identifier.GetLocation(), ShouldWarn: true);
                })
            .Where(static c => c.ShouldWarn);

        context.RegisterSourceOutput(unmarkedDerived, static (spc, c) =>
            spc.ReportDiagnostic(Diagnostic.Create(Diagnostics.UnmarkedDerivedFromTaciturn, c.Location, c.Name)));
    }

    private readonly record struct DerivedCandidate(string Name, Location Location, bool ShouldWarn);

    private static string Encode((string Name, bool IsPlain) m) => m.IsPlain ? m.Name + PlainMarker : m.Name;

    // Plain substring, not the C# 8 index/range operators (encoded[^1], [..^1]):
    // netstandard2.0 has no System.Index/System.Range without yet another
    // polyfill alongside IsExternalInit, and this needs no new one.
    private static (string Name, bool IsPlain) Decode(string encoded) =>
        encoded[encoded.Length - 1] == PlainMarker
            ? (encoded.Substring(0, encoded.Length - 1), true)
            : (encoded, false);

    /// <summary>
    /// Everything Execute/Render need, extracted at transform-time so nothing
    /// downstream ever touches a symbol or syntax node. Every field here compares
    /// by value, which is what lets the incremental pipeline actually cache.
    /// </summary>
    private readonly record struct Candidate(
        string Name,
        string TypeParametersDisplay,
        string? Namespace,
        bool IsPartial,
        bool IsRecord,
        bool IsRecordStruct,
        bool IsSealed,
        bool DerivesFromAnotherRecord,
        bool AlreadyHasPrintMembersOrToString,
        string EncodedMembers,
        Location Location);

    private enum Signature { Private, ProtectedVirtual, ProtectedOverride }

    /// <summary>
    /// The four cases from the design spec collapse to three distinct signatures:
    /// a record struct and a sealed record deriving from object both need
    /// `private`, since neither can be further derived from. Anything deriving
    /// from another record needs `protected override` (chaining base.PrintMembers)
    /// regardless of its own sealed-ness - only a non-sealed record deriving
    /// directly from object needs the fourth case, `protected virtual`. This is
    /// exhaustive over every possible C# record shape, so nothing falls through.
    /// </summary>
    private static Signature SelectSignature(Candidate c)
    {
        if (c.IsRecordStruct) return Signature.Private;
        if (c.DerivesFromAnotherRecord) return Signature.ProtectedOverride;
        return c.IsSealed ? Signature.Private : Signature.ProtectedVirtual;
    }

    private static void Execute(SourceProductionContext context, Candidate candidate)
    {
        if (!candidate.IsPartial)
        {
            context.ReportDiagnostic(Diagnostic.Create(Diagnostics.NotPartial, candidate.Location, candidate.Name));
            return;
        }

        if (!candidate.IsRecord)
        {
            context.ReportDiagnostic(Diagnostic.Create(Diagnostics.NotRecord, candidate.Location, candidate.Name));
            return;
        }

        if (candidate.AlreadyHasPrintMembersOrToString)
        {
            context.ReportDiagnostic(Diagnostic.Create(Diagnostics.AlreadyDeclared, candidate.Location, candidate.Name));
            return;
        }

        var members = candidate.EncodedMembers.Length == 0
            ? ImmutableArray<(string Name, bool IsPlain)>.Empty
            : candidate.EncodedMembers.Split(' ').Select(Decode).ToImmutableArray();

        var source = Render(candidate, SelectSignature(candidate), members);
        context.AddSource($"{candidate.Name}_Taciturn.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private static bool HasUserDeclaredPrintMembersOrToString(INamedTypeSymbol symbol)
    {
        bool HandWritten(ISymbol m) => !m.IsImplicitlyDeclared;

        if (symbol.GetMembers("PrintMembers").Any(HandWritten))
            return true;

        return symbol.GetMembers("ToString")
            .OfType<IMethodSymbol>()
            .Any(m => HandWritten(m) && m.Parameters.Length == 0);
    }

    private static bool HasPlainAttribute(ISymbol member) =>
        member.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == PlainAttributeFullName);

    /// <summary>
    /// Public instance properties with a public getter, plus public instance fields,
    /// in declaration order — the same set System.Text.Json / the record's own
    /// synthesized PrintMembers would print. Compiler-generated backing fields for
    /// auto-properties are excluded via IsImplicitlyDeclared. Each is paired with
    /// whether it carries [Plain] - on a positional record parameter, that means
    /// [property: Plain], since the attribute targets the synthesized property,
    /// never the parameter itself.
    /// </summary>
    private static ImmutableArray<(string Name, bool IsPlain)> GetPrintableMembers(INamedTypeSymbol symbol)
    {
        var builder = ImmutableArray.CreateBuilder<(string, bool)>();

        foreach (var member in symbol.GetMembers())
        {
            if (member.IsStatic || member.IsImplicitlyDeclared)
                continue;

            switch (member)
            {
                case IPropertySymbol { IsIndexer: false } prop
                    when prop.DeclaredAccessibility == Accessibility.Public
                         && prop.GetMethod is { DeclaredAccessibility: Accessibility.Public }:
                    builder.Add((prop.Name, HasPlainAttribute(prop)));
                    break;

                case IFieldSymbol field
                    when field.DeclaredAccessibility == Accessibility.Public:
                    builder.Add((field.Name, HasPlainAttribute(field)));
                    break;
            }
        }

        return builder.ToImmutable();
    }

    private static string Render(Candidate candidate, Signature signature, ImmutableArray<(string Name, bool IsPlain)> members)
    {
        string keyword = candidate.IsRecordStruct ? "record struct" : "record";
        string modifiers = signature switch
        {
            Signature.Private => "private",
            Signature.ProtectedVirtual => "protected virtual",
            Signature.ProtectedOverride => "protected override",
            _ => throw new System.InvalidOperationException($"Unhandled {nameof(Signature)}: {signature}"),
        };
        bool chainsBase = signature == Signature.ProtectedOverride;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by Taciturn — members without [Plain] are redacted; members with it print their real value.");
        sb.AppendLine("#nullable enable");

        bool hasNamespace = candidate.Namespace is { Length: > 0 };
        if (hasNamespace)
        {
            sb.Append("namespace ").AppendLine(candidate.Namespace);
            sb.AppendLine("{");
        }

        string indent = hasNamespace ? "    " : "";
        string typeArgs = candidate.TypeParametersDisplay.Length > 0 ? $"<{candidate.TypeParametersDisplay}>" : "";
        // Unbound-generic typeof syntax for the attribute argument: arity commas,
        // no type names - e.g. <T, U> becomes <,> in typeof(Wrapper<,>.DebugView).
        string unboundTypeArgs = candidate.TypeParametersDisplay.Length > 0
            ? "<" + new string(',', candidate.TypeParametersDisplay.Split(',').Length - 1) + ">"
            : "";
        string debugViewName = candidate.Name + "DebugView";

        sb.Append(indent)
          .Append("[System.Diagnostics.DebuggerTypeProxy(typeof(")
          .Append(candidate.Name).Append(unboundTypeArgs).Append('.').Append(debugViewName)
          .AppendLine("))]");
        sb.Append(indent).Append("partial ").Append(keyword).Append(' ').Append(candidate.Name).Append(typeArgs);
        sb.AppendLine();
        sb.Append(indent).AppendLine("{");
        sb.Append(indent).Append("    ").Append(modifiers).AppendLine(" bool PrintMembers(System.Text.StringBuilder builder)");
        sb.Append(indent).AppendLine("    {");

        // "printedAny" starts from whatever the base chain already wrote (false
        // for the two non-chaining signatures), then each own member appends a
        // leading ", " only when something - base or an earlier own member - has
        // already been written. This is what keeps a comma from appearing before
        // the first thing on the line, or a stray trailing separator when this
        // type's own member list is empty but the base printed something.
        if (chainsBase)
        {
            sb.Append(indent).AppendLine("        bool printedAny = base.PrintMembers(builder);");
        }
        else
        {
            sb.Append(indent).AppendLine("        bool printedAny = false;");
        }

        foreach (var (name, isPlain) in members)
        {
            sb.Append(indent).AppendLine("        if (printedAny) builder.Append(\", \");");
            if (isPlain)
            {
                // The real value, via the member's own name as an expression -
                // not a string literal - so it goes through whatever ToString()
                // that value's type actually has.
                sb.Append(indent).Append("        builder.Append(\"").Append(name).Append(" = \").Append(").Append(name).AppendLine(");");
            }
            else
            {
                sb.Append(indent)
                  .Append("        builder.Append(\"").Append(name).Append(" = \").Append(\"«redacted»\");")
                  .AppendLine();
            }
            sb.Append(indent).AppendLine("        printedAny = true;");
        }

        sb.Append(indent).AppendLine("        return printedAny;");
        sb.Append(indent).AppendLine("    }");

        // Nested so it can see the containing type's own type parameters without
        // restating them, and so a hover in the debugger shows exactly the same
        // «redacted»/real-value split ToString() does - the whole point of a
        // debugger proxy is that a breakpoint can't bypass what a log line can't.
        sb.Append(indent).Append("    private sealed class ").Append(debugViewName).AppendLine();
        sb.Append(indent).AppendLine("    {");
        sb.Append(indent).Append("        private readonly ").Append(candidate.Name).Append(typeArgs).AppendLine(" _value;");
        sb.Append(indent).Append("        public ").Append(debugViewName).Append('(').Append(candidate.Name).Append(typeArgs).AppendLine(" value) => _value = value;");
        foreach (var (name, isPlain) in members)
        {
            string expr = isPlain ? $"_value.{name}" : "\"«redacted»\"";
            sb.Append(indent).Append("        public object? ").Append(name).Append(" => ").Append(expr).AppendLine(";");
        }
        sb.Append(indent).AppendLine("    }");

        sb.Append(indent).AppendLine("}");

        if (hasNamespace)
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }
}
